version: '3.0'

services:
  web:
    build: .
      
    image: ${DOCKER_USER_ID}/hw6

  production:

    image: ${DOCKER_USER_ID}/hw6:${BUILD_NUMBER}
    restart: always
    volumes:
      -"/home/jenkins:/var/jenkins_home/workspace/hw6"
    ports:
      - "80:80"