version: '3.0'

services:
  nginx-app:
    build: .
      
    image: ${DOCKER_USER_ID}/hw6
    container_name: nginx-app

  production:

    image: ${DOCKER_USER_ID}/hw6:${BUILD_NUMBER}
    restars: always
    ports:
      - "80:80"