version: '3.0'

services:
  nginx-app:
    build: .
      
    image: ${DOCKER_USER_ID}/hw5

  production:

    image: ${DOCKER_USER_ID}/hw5:${BUILD_NUMBER}
    restart: always
    ports:
      - "80:80"