version: '3.0'

services:
  nginx-app:
    build: .
    ports:
      - "80:80"
    image: ${DOCKER_USER_ID}/nginx
  production:

    image: ${DOCKER_USER_ID}/nginx:${BUILD_NUMBER}


    ports:
      - "80:80"
  
  